# Generated by Django 4.2.7 on 2025-11-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=20)),
                ('poster_url', models.URLField()),
                ('youtube_trailer', models.URLField(blank=True)),
            ],
        ),
    ]
