# Generated by Django 5.2.8 on 2026-03-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube_trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('VF', 'Français'), ('VOSTFR', 'VO Sous-titrée FR'), ('VO', 'Version Originale')], default='VF', max_length=10)),
                ('quality', models.CharField(choices=[('1080p', 'Full HD (1080p)'), ('720p', 'HD (720p)'), ('480p', 'SD (480p)'), ('4K', 'Ultra HD (4K)')], default='1080p', max_length=10)),
                ('source_type', models.CharField(choices=[('EMBED', 'Embed (Iframe)'), ('M3U8', 'HLS Stream (.m3u8)'), ('MP4', 'Direct File (.mp4)'), ('MAGNET', 'Magnet Link')], default='EMBED', max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='movies.movie')),
            ],
        ),
    ]
