# Generated by Django 5.2.8 on 2026-03-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_youtube_trailer_videosource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube_trailer',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='VideoSource',
        ),
    ]
